* ISD BI-WEEKLY REPORT

- NAME: John Morgan
- BRANCH : MCAB
- ERIOD ENDING: <2017-12-05 Tue>
- PROJECT NAME: Multilang
- RESEARCH QUESTION FOCUS: How can AI, machine learning and data from well-resourced languages be leveraged to build Automatic Speech Recognition systems for Low Resource Languages. 
* MISSION ACTIVITIES SINCE LAST REPORT:
- Trained ASR systems for most of the 19 GlobalPhone languages and used these systems to align speech vectors with model labels.
- Contributed writing an abstract for a presentation and paper at a Machine Translation Conference. 
- Produced a set of hypothesis translations for unlabeled Arabic speech corpus and passed it to the Human Expert for corrections.
* KEY CUSTOMER/STAKEHOLDER ENGAGEMENTS:
- ORG/POC

* OUTCOME/NEXT STEPS:
Train a global i-vector extractor on the data from the GlobalPhone languages.
* UPCOMING EVENTS:
- DATE:
- EVENT:
- POC/STAFF:

* METRICS:
PAPER         BOOK CHAPTER         SW               CONFERENCE             DEMO  
 Citation

* OUTREACH:
- OCOH         POST DOC                     STEM            SUMMER INTERN             USMA OTHER
Citation (include dates, recipient, focus of effort, impact, etc.)
Citation

* TRAVEL
NO
-  REMARKS (Date, Location, Purpose, Organization, Who Visited, Reason, Outcome)
