* <2018-04-11 Wed>
- NAME: John Morgan
- BRANCH : MCAB
- PERIOD ENDING: <2018-04-11 Wed>

- PROJECT NAME: Multi-Task Learning for Automatic Speech Recognition  of Low Resource Languages 
- RESEARCH QUESTION FOCUS: How can learning be transfered from one resource to another.
** MISSION ACTIVITIES SINCE LAST REPORT:
A minimal example of the MTL method was successfully implemented.

** KEY CUSTOMER/STAKEHOLDER ENGAGEMENTS:
- ORG/POC

** OUTCOME/NEXT STEPS:

Repeat this experiment on a different language pair. Namely, English and African Accented French instead of English and North African Accented Modern Standar Arabic.
** UPCOMING EVENTS:
- DATE:
- EVENT:
- POC/STAFF:

** METRICS:
Tasks:
1. Librispeech: 960 hours of read English.
2. Tunisian_MSA: 10 hours of recitations and answers to questions in Modern Standard Arabic spoken by Tunisians

Tested on 4 speakers, 3 Libyan males and 1 Tunisian female.

Tunisian_MSA Baseline:
%WER 11.03 [ 726 / 6584, 61 ins, 237 del, 428 sub ] exp/chain/tdnn1a_sp_online/decode_test/wer_13_0.0

Test Results:
%WER 7.12 [ 469 / 6584, 100 ins, 124 del, 245 sub ] exp/multi/Tunisian_MSA/decode_test/wer_13_0.0

- PAPER         BOOK CHAPTER         SW               CONFERENCE             DEMO  

- Citation
** OUTREACH:
- OCOH         POST DOC                     STEM            SUMMER INTERN             USMA OTHER

I participated  in 3 interviews of candidates for summer student internships.
Citation (include dates, recipient, focus of effort, impact, etc.)
Citation

** TRAVEL
NO
-  REMARKS (Date, Location, Purpose, Organization, Who Visited, Reason, Outcome)

* ISD BI-WEEKLY REPORT <2018-03-15 Wed>

- NAME: John Morgan
- BRANCH : MCAB
- PERIOD ENDING: <2018-03-15 Wed>

- PROJECT NAME: Multi-Task Learning for Automatic Speech Recognition  of Low Resource Languages 
- RESEARCH QUESTION FOCUS: How can learning be transfered from one resource to another.
** MISSION ACTIVITIES SINCE LAST REPORT:
A Colloquium presentation was made.
Several people provided feedback and expressed possible future collaborations.

** KEY CUSTOMER/STAKEHOLDER ENGAGEMENTS:
- ORG/POC

** OUTCOME/NEXT STEPS:

** UPCOMING EVENTS:
- DATE:
- EVENT:
- POC/STAFF:

** METRICS:

- PAPER         BOOK CHAPTER         SW               CONFERENCE             DEMO  

- Citation
** OUTREACH:
- OCOH         POST DOC                     STEM            SUMMER INTERN             USMA OTHER
Citation (include dates, recipient, focus of effort, impact, etc.)
Citation

** TRAVEL
NO
-  REMARKS (Date, Location, Purpose, Organization, Who Visited, Reason, Outcome)
		DTK_PROGRAM=espeak
		export DTK_PROGRAM

* ISD BI-WEEKLY REPORT <2018-01-31 Wed>

- NAME: John Morgan
- BRANCH : MCAB
- PERIOD ENDING: <2018-01-31 Wed>

- PROJECT NAME: Multi-Task Learning for Automatic Speech Recognition  of Low Resource Languages 
- RESEARCH QUESTION FOCUS: How can learning be transfered from one resource to another.
** MISSION ACTIVITIES SINCE LAST REPORT:
Positive results were obtained on a small experiment.
MTL was run on 3 corpora: Global Phone Arabic, Tuniseen and GALE Arabic.
The first 2 corpora are read speech  and the third is broadcast news.

** KEY CUSTOMER/STAKEHOLDER ENGAGEMENTS:
- ORG/POC

** OUTCOME/NEXT STEPS:
Word error rate was lowered on the GP Arabic dev set to a better score than that achieved with chain models.
Next, we should try this on a different set of corpora and multiple languages (Mandarin?). 
** UPCOMING EVENTS:
- DATE:
- EVENT:
- POC/STAFF:

** METRICS:

| language   | tri3b WER | chain WER | MTL gp_arabic softunisia | gp_arabic softunisia GALE Arabic|
| GP Arabic dev |     55.98 |     51.17 | 51.73 | 50.95 |

- PAPER         BOOK CHAPTER         SW               CONFERENCE             DEMO  

- Citation
** OUTREACH:
- OCOH         POST DOC                     STEM            SUMMER INTERN             USMA OTHER
Citation (include dates, recipient, focus of effort, impact, etc.)
Citation

** TRAVEL
NO
-  REMARKS (Date, Location, Purpose, Organization, Who Visited, Reason, Outcome)
		DTK_PROGRAM=espeak
		export DTK_PROGRAM

* ISD BI-WEEKLY REPORT <2018-01-18 Thu>

- NAME: John Morgan
- BRANCH : MCAB
- PERIOD ENDING: <2018-01-18 Thu>
- PROJECT NAME: Heroico
- RESEARCH QUESTION FOCUS: How can learning be transfered from one resource to another.
** MISSION ACTIVITIES SINCE LAST REPORT:
- Recipe for the Heroico corpus was merged into the Kaldi repository. 

** KEY CUSTOMER/STAKEHOLDER ENGAGEMENTS:
- ORG/POC
Dr. Daniel Povey
** OUTCOME/NEXT STEPS:
Use Heroico corpus in Multilang research project.
** UPCOMING EVENTS:
- DATE:
- EVENT:
- POC/STAFF:

** METRICS:
PAPER         BOOK CHAPTER         SW               CONFERENCE             DEMO  
Recipe is publically available at:
https://github.com/kaldi-asr/kaldi.git
Citation
** OUTREACH:
- OCOH         POST DOC                     STEM            SUMMER INTERN             USMA OTHER
Citation (include dates, recipient, focus of effort, impact, etc.)
Citation

** TRAVEL
NO
-  REMARKS (Date, Location, Purpose, Organization, Who Visited, Reason, Outcome)
