1. TECHNICAL Objectives (Weight 30)
A. Acoustic Models for Low Resource Languages
Adapt the Kaldi multilang recipe to build acoustic models for  a target low resource language  given resources from many other source languages. 

Specific Rating tasks:
Modify the Kaldi multilang recipe    from its original keyword spotting task to the Speech to Speech (S2S) task.
Build 18 ASR systems from source language resources in the GlobalPhone corpus and government owned corpora (see corpus curation task below).
Setup experiment to evaluate effectiveness of the multilang approach. 

B. Corpus Curation
Curate four government owned speech corpora.

Specific Rating Tasks:
Prepare Arabic, French, German and Russian speech data  for   use in the multilang project listed above.
Write Kaldi recipes for each language corpus.
Submit recipes for publication in Kaldi repository.
Publish data, lexicons and recipes in ARL NSRL repository.

C. Speech to Speech Technology
Investigate S2S hardware restrictions and software solutions with the goal of contributing optimized components. 

Specific Rating Tasks:
Study methods for performing online or real time ASR processing and produce ASR components that are optimized to work with these methods. 
Study methods for integrating ASR and MT components in S2S applications and tailor our products to conform to these methods.
Study methods for making S2S ASR highly responsive and accurate and use results of investigations to guide our choices of models and algorithms. 



(2) COOPERATION (Weight 10)

A. Cooperate with colleagues.

Specific Rating Tasks:
Collaborate with Steve LaRocca in first quarter  to write papers that report on advances made in our projects. 
Collaborate with the Basic Research team and CERDEC by contributing speech recognition components to Human Robot communication efforts. 

(3) COMMUNICATIONS  (Weight 30)

A. Publish papers and reports

Specific Rating Tasks:
Write a TR with Steve LaRocca in the first quarter documenting projects. 
Write journal paper with Steve LaRocca that reports on multilang project results.

B. Activity Reports
Write weekly reports to help guide research and to recored progress .

C. Establish Professional Communication Channels with Scientists contributing to Kaldi project.

Specific Rating Tasks:
Contribute algorithm to Kaldi

(4) MGMT. OF TIME & RESOURCES (Weight 15)

A. Curate and archive our own valuable  speech and text corpora on our branch storage disks. 


Specific Rating Tasks:
Format the data so that the corpora that can be made publically available are ready to be transfered. 
Organize the data so that it is easy to access from recipes running on connected branch machines.
Stay abreast of possible areas where hardware upgrades could improve work efficiency. 

(5) CUSTOMER RELATIONS (Weight 15)

Establish relationships with MFLTS and CERDEC to remain aware of Army requirements.
Establish contacts with researchers in the ASR and NLP fields. 
Establish contacts with s2s application developers.

(6) TECH TRANSITION (Weight 10)

Contribute recipes for building ASR systems with our corpora to the MFLTS. 
Transition ASR components and our other products to USA Army Africa and MFLTS.  

(7) DIVERSITY: 
Support ARL's diversity initiatives by participating in locally-sponsored diversity training, broad outreach, and/or special emphasis programs to increase personal awareness and understanding of the various cultures that exist among laboratory employees. 

(8) SHARP: 
Support leadership's efforts to address and prevent sexual harassment and sexual assault and ensure a respectful work environment for all. 
Demonstrate support for the SHARP program by actively participating in required training and other educational programs. 
Intervene and appropriately respond to any instances of sexual harassment or sexual assault and encourage others to do the same.

* 2016-2017: 
** 1. TECHNICAL COMPETENCE
*** ASR Adaptation:
It is not clear that the advances made last year can be implemented in applications that would directly benefit the Army. 
This year I propose to capitalize on last year's successes by investigating ASR models that have well defined pathways to implementation  in speech to speech devices. 
I will focus on developing models that result in software that can be demoed with realtime interaction. 

*** kaldi:

The ASR systems I have built this year are based on HMMs and SGMMs. 
I will consider these systems as baselines for the work I will do using neural network models. 
I will continue developing with the Kaldi ASR toolkit. 
Specifically, I will implement systems with the following kaldi named models:
Bottle Neck Features
Chain Models
nnet2
nnet3
TDNNs
RBMs
Eesen end to end rnn and lstm models.

I will replicate for Arabic the work I did last year for French. 
That is, I will adapt Standard Arabic models to Tunisian accented speech in the same way I adapted European French to African accents.
I will make an effort to improve the language modeling component of the French and Arabic systems I develop with Kaldi.

*** Lexicon expansion
I will attempt to use the work done in the Babel project for automatic lexicon expansion in our African French and Tunisian Arabic corpora. 
This might involve automatic syllable boundary labeling. 

*** Afghan Languages 

I will build ASR systems for Dari and Pashto. 
I will leverage resources produced by the babel project for Pashto. 
I will work with Hazrat Ghulam Jahed on building high quality Dari and Pashto ASR systems.

*** Research:
**** Variable Structured computational graphs.
Many models used in NLP applications have a network of connected nodes. 
Training these networks has been restricted to computing weights associated with the connections. 
The topology of the networks has largely remained fixed. 
Lately there have been attempts to develop training methods that change the network topology with each training example. 
I propose to learn to use a toolkit called DyNet (or one like it) that is designed to build systems with variable graph structures. 

I plan on using DyNet or a toolkit similar to it to build a Machine Translation System and to compare its performance with systems built with other reference toolkits like Joshua, Moses, Tensorflow, etc.  
** 2. COOPERATION

Collaborate with colleagues to write papers that report on advances made in our projects. 
Collaborate with the Basic Research team by contributing speech recognition components to efforts such as the bot language project. 
** 3. COMMUNICATIONS

Write weekly activity reports to team members to keep them up to date on my work. 
Read and comment on reports made by my team and branch mates.

** 4. MGMT. OF TIME & RESOURCES

Set aside time during the day to practice some kind of  activity for physical fitness. 
Stay abreast of possible areas where hardware upgrades could improve work efficiency. 
** 5. CUSTOMER RELATIONS

Establish relationships with MFLTS and CERDEC to remain aware of Army requirements.
Establish contacts with researchers in the ASR and NLP fields. 
Establish contacts with s2s device manufacturers.

** 6. TECH TRANSITION

Contribute recipes for building ASR systems with our corpora to the MFLTS. 
Transition ASR components and our other products to USA Army Africa and MFLTS.  
** 7. DIVERSITY: 
Support ARL's diversity initiatives by participating in locally-sponsored diversity training, broad outreach, and/or special emphasis programs to increase personal awareness and understanding of the various cultures that exist among laboratory employees. 
** 8. SHARP: 
Support leadership's efforts to address and prevent sexual harassment and sexual assault and ensure a respectful work environment for all. 
Demonstrate support for the SHARP program by actively participating in required training and other educational programs. 
Intervene and appropriately respond to any instances of sexual harassment or sexual assault and encourage others to do the same.
